### ISSUE TITLE
Configure exempt_methods so we can exclude 'OPTIONS' requests

### ISSUE THREAD

**Issue by tuler** [jhildreth/falcon-jwt-checker#1]
When used in tandem with [falcon-cors](https://github.com/lwcolton/falcon-cors) I need a way to "short-circuit" the jwt-checker middleware for pre-flight 'OPTIONS' requests, as they are handled by that middleware.

**Comment by jhildreth** [comment]
That's an interesting case. I haven't needed to do anything with CORS yet, so thanks for the suggestion! I'll look into it a bit more, but at a first glance it seems like this would make sense.

**Comment by jhildreth** [comment]
I've added this option in [0.1.2](https://github.com/jhildreth/falcon-jwt-checker/releases/tag/0.1.2). I'm going to close the issue - but I'd definitely appreciate hearing back if this meets what you were looking for!

**Comment by tuler** [comment]
Perfect, it's exactly like my personal patch. Thanks!

**Comment by jhildreth** [comment]
Great, glad to hear it!
