### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by fizzgig242** [jhildreth/falcon-jwt-checker#7]
Hey there,

would it be possible to create a little example project that is using falcon-jwt-checker?

I am not able to retrieve data for a simple route that is selecting data from a sqlite database.

Maybe it has something to do with my GET request using Postman. I try to create the JWT token with the debugger at jwt.io but it is not working.

**Comment by jhildreth** [comment]
Hi there,

Thanks for the suggestion! An example project is probably not something I can put time towards right now, but the snippets in the readme should get you pretty close.

If you can provide some more detail about what isn't working, I'd be happy to try to help. In particular, are you getting any output in the console of your Falcon server when you make the request?

**Comment by fizzgig242** [comment]
I got it working.

I used your example code in my project but did not include audience "aud" in my payload. :D

**Comment by jhildreth** [comment]
Awesome, glad to hear it!
